[package]
name = "dont-repeat-yourself"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta-ext = "0.4.4"
directories = "5.0.1"
eframe = "0.29.1"
serde = "1.0.213"
serde_json = "1.0.132"
